update

diff --git a/.github/workflows/premetheus-grafana.yml b/.github/workflows/premetheus-grafana.yml
--- a/.github/workflows/premetheus-grafana.yml
+++ b/.github/workflows/premetheus-grafana.yml
@@ -16,17 +16,6 @@ jobs:
         with:
           python-version: 3.x
 
-      - name: Check and Install AWS CLI
-        run: |
-            if ! command -v aws &> /dev/null
-            then
-              echo "AWS CLI not found. Installing..."
-              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-              unzip awscliv2.zip
-              sudo ./aws/install
-            fi
-        shell: bash
-
       - name: Set up AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -51,7 +40,18 @@ jobs:
         run: |
           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
           helm repo update
-          helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus
+          helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus --timeout 30m
+
+      - name: Check installation status
+        run: |
+          if ! kubectl get pods -n prometheus -l "app=prometheus"; then
+            echo "Prometheus pods not found!"
+            exit 1
+          fi
+          if ! kubectl get pods -n prometheus -l "app=grafana"; then
+            echo "Grafana pods not found!"
+            exit 1
+          fi
 
       #- name: Port-forward Prometheus
       #  run: kubectl port-forward -n prometheus svc/prometheus-prometheus-operated 9090:9090
