add workflows Prometheus and Grafana

diff --git a/.github/workflows/premetheus-grafana.yml b/.github/workflows/premetheus-grafana.yml
--- a/.github/workflows/premetheus-grafana.yml
+++ b/.github/workflows/premetheus-grafana.yml
@@ -16,23 +16,26 @@ jobs:
         with:
           python-version: 3.x
 
-      - name: Check and Install Az CLI
+      - name: Check and Install AWS CLI
         run: |
-          if ! command -v az &> /dev/null
-          then
-            echo "Az CLI not found. Installing..."
-            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-          fi
+            if ! command -v aws &> /dev/null
+            then
+              echo "AWS CLI not found. Installing..."
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+            fi
         shell: bash
 
-      - name: Login to Azure
-        id: azure_login
-        uses: azure/login@v1
+      - name: Set up AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
 
       - name: Get credentials
-        run: az aks get-credentials --resource-group re-teoSchool-djiby --name aks-djiby
+        run: aws eks --region ${AWS_REGION} update-kubeconfig --name djiby-eks-cluster
 
       - name: Install Helm
         run: |
